# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

puts "Euler project Solution 2"
$a = []
$a[0] = 0
$a[1] = 1

def sol2
  r = 0
  i = 0
  while i <= 400
    c = fib(i)
    if c.even?
  	  r += c
    end
    i += 1
    break if c >= 4000000
  end
  puts r
end

def fib(n)
  $a[n] = $a[n-1] + $a[n-2]
end

sol2

puts "End of Solution 2"